stages:
- name: Etcd
  steps:
  - applyAppConfig:
      catalogTemplate: cattle-global-data:googleapis-etcd-operator
      version: 0.9.1
      answers:
        customResources.createEtcdClusterCRD: "true"
      name: etcd-operator
      targetNamespace: srv
- name: Redis
  steps:
  - applyAppConfig:
      catalogTemplate: cattle-global-data:library-redis
      version: 9.0.2
      answers:
        cluster.slaveCount: "2"
        master.persistence.enabled: "true"
        slave.persistence.enabled: "true"
      name: redis
      targetNamespace: srv
- name: Config
  steps:
  - applyYamlConfig:
      path: ./config.yaml
- name: Micro
  steps:
  - applyYamlConfig:
      path: ./app/micro-api.yaml
- name: UserMariadb
  steps:
  - applyAppConfig:
      catalogTemplate: cattle-global-data:library-mariadb
      version: 6.7.4
      answers:
        db.name: user
        db.user: user
        service.type: ClusterIP
        slave.replicas: "2"
      name: user
      targetNamespace: srv
- name: User
  steps:
  - applyYamlConfig:
      path: ./app/user.yaml
- name: UserApi
  steps:
  - applyYamlConfig:
      path: ./app/user-api.yaml
notification: {}
