stages:
- name: Redis
  steps:
  - applyAppConfig:
      catalogTemplate: cattle-global-data:library-redis
      version: 9.0.2
      answers:
        cluster.slaveCount: "2"
        master.persistence.enabled: "true"
        slave.persistence.enabled: "true"
      name: redis
      targetNamespace: api
- name: Config
  steps:
  - applyYamlConfig:
      path: ./config.yaml
- name: Micro
  steps:
  - applyYamlConfig:
      path: ./app/micro-api.yaml
- name: UserMariadb
  steps:
  - applyAppConfig:
      catalogTemplate: cattle-global-data:library-mariadb
      version: 6.7.4
      answers:
        db.name: user
        db.user: user
        service.type: ClusterIP
        slave.replicas: "2"
      name: user
      targetNamespace: srv
- name: User
  steps:
  - applyYamlConfig:
      path: ./app/user.yaml
- name: UserApi
  steps:
  - applyYamlConfig:
      path: ./app/user-api.yaml
- name: PayMariadb
  steps:
  - applyAppConfig:
      catalogTemplate: cattle-global-data:library-mariadb
      version: 6.7.4
      answers:
        db.name: pay
        db.user: pay
        service.type: ClusterIP
        slave.replicas: "2"
      name: pay
      targetNamespace: srv
- name: Pay
  steps:
  - applyYamlConfig:
      path: ./app/pay.yaml
- name: PayApi
  steps:
  - applyYamlConfig:
      path: ./app/pay-api.yaml
notification: {}
