# 负载均衡
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: microapi
  namespace: api
spec:
  rules:
  - host: xip.io
    http:
      paths:
        - backend:
            serviceName: microapi
            servicePort: http
---
apiVersion: v1
kind: Service
metadata:
  name: microapi
  namespace: api
spec:
  selector:
    app: microapi
  type: ClusterIP
  ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: microapi
  namespace: api
  labels:
    app: microapi
spec:
  replicas: 3
  selector:
    matchLabels:
      app: microapi
  template:
    metadata:
      labels:
        app: microapi
    spec:
      serviceAccountName: microapi-services
      containers:
        - name: microapi
          image: micro/micro:v2.0.0
          imagePullPolicy: Always
          args:
            - "api"
            - "--handler=rpc"
          env:
          - name: MICRO_API_NAMESPACE
            value: go.micro.api
          - name: MICRO_SERVER_NAME
            value: microapi
          - name: MICRO_SERVER_ADDRESS
            value: 0.0.0.0:8989
          - name: MICRO_ENABLE_STATS
            value: "true"
          - name: MICRO_REGISTRY
            value: kubernetes
          ports:
          - containerPort: 8080
            name: http
            protocol: TCP
        - name: health
          command: [
            "/health",
            "--health_address=0.0.0.0:8081",
            "--server_name=microapi",
            "--server_address=0.0.0.0:8989"
          ]
          image: microhq/health:kubernetes
          livenessProbe:
            httpGet:
              path: /health
              port: 8081
            initialDelaySeconds: 3
            periodSeconds: 3


