

kind: Service
apiVersion: v1
metadata:
  name: ui
  namespace: srv
spec:
  selector:
    app: ui
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 80
      name: http
      targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ui
  namespace: srv
  labels:
    app: ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ui
  template:
    metadata:
      labels:
        app: ui
    spec:
      serviceAccountName: micro-services
      imagePullSecrets:
      - name: pipeline-docker-registry
      containers:
        - name: ui
          image: registry.cn-hangzhou.aliyuncs.com/lecex/electron
          imagePullPolicy: Always
          env:
            - name: BASE_URL
              valueFrom:
                secretKeyRef:
                  key: base-url
                  name: ui
          ports:
          - containerPort: 80
            name: http
            protocol: TCP
